server.port=8081
spring.application.name=core-service

spring.datasource.url=jdbc:postgresql://ep-flat-term-amd10uot.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_eFE7tCm2fiXG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true